CREATE DATABASE mainapp;
CREATE USER mainapp_user WITH ENCRYPTED PASSWORD 'YOUR_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE mainapp TO mainapp_user;

CREATE DATABASE strapi_db;
CREATE USER strapi_user WITH ENCRYPTED PASSWORD 'YOUR_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE strapi_db TO strapi_user;

\c strapi_db
GRANT ALL ON SCHEMA public TO strapi_user;